base:
  project: winequality-project
  random_state: 42
  target_col: quality

data_source:
  s3_source: data_given/wine_quality.csv

load_data:
  raw_dataset_csv: data/raw/wine_quality.csv

split_data:
  train_path: data/processed/train_wine_quality.csv
  test_path: data/processed/test_wine_quality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      # alpha: 0.88
      # l1_ratio: 0.89
      # alpha: 0.5
      # l1_ratio: 0.9
      # alpha: 0.9
      # l1_ratio: 0.5
      alpha: 0.5
      l1_ratio: 0.5

model_dir: saved_models

reports:
  scores: reports/scores.json
  params: reports/params.json

webapp_model_dir: prediction_service\model\model.joblib
